[package]
name = "weverse-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
enigo = "0.5.0"
glib = "0.21.0"
gtk4 = "0.10.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
