[package]
name = "weverse-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
enigo = { version = "0.5.0", features = ["wayland", "libei"] }
glib = "0.21.1"
gtk4 = "0.10.0"
slab = "0.4.11"

[profile.release]
strip = true
lto = true
codegen-units = 1
